version: "3.9"

services:
  app_vet:
    build: clinica_veterinaria
    mem_limit: 512m
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - clinica_vet
  clinica_vet:
    image: mysql
    container_name: clinica_vet
    environment:
      MYSQL_ROOT_PASSWORD: cristian123
      MYSQL_DATABASE: clinica_veterinaria
      MYSQL_USER: cguerreros
      MYSQL_PASSWORD: cristian123
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10


